version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  groups:
    pyiron:
      applies-to: version-updates
      patterns:
        - "pyiron*"
  open-pull-requests-limit: 10
