jobs:
  include:
    - stage: Build Docker Images
      install:
        - export TODAY=$(date +%F)
        - docker build -t pyiron/base:latest base/
        - docker tag pyiron/base:latest pyiron/base:"$TODAY"
        - docker build -t pyiron/md:latest md/
        - docker tag pyiron/md:latest pyiron/md:"$TODAY"
        - docker build -t pyiron/pyiron:latest pyiron/
        - docker tag pyiron/pyiron:latest pyiron/pyiron:"$TODAY"
        - docker build -t pyiron/experimental:latest experimental/
        - docker tag pyiron/experimental:latest pyiron/experimental:"$TODAY"
        - docker build -t pyiron/damask:latest damask/
        - docker tag pyiron/damask:latest pyiron/damask:"$TODAY"
        - docker images
      script: 
        - if [ "$TRAVIS_BRANCH" != "master" ]; then docker run --rm pyiron/base /bin/bash -c 'source /opt/conda/bin/activate; i=0; for f in $(ls ~/*.ipynb); do jupyter nbconvert --ExecutePreprocessor.timeout=9999999 --to notebook --execute $f || i=$((i+1)); done; if [ $i -gt 0 ]; then exit 1; fi;'; fi;    
        - if [ "$TRAVIS_BRANCH" != "master" ]; then docker run --rm pyiron/pyiron /bin/bash -c 'source /opt/conda/bin/activate; i=0; for f in $(ls ~/*.ipynb); do jupyter nbconvert --ExecutePreprocessor.timeout=9999999 --to notebook --execute $f || i=$((i+1)); done; if [ $i -gt 0 ]; then exit 1; fi;'; fi;
        - if [ "$TRAVIS_BRANCH" != "master" ]; then docker run --rm pyiron/experimental /bin/bash -c 'source /opt/conda/bin/activate; i=0; for f in $(ls ~/*.ipynb); do jupyter nbconvert --ExecutePreprocessor.timeout=9999999 --to notebook --execute $f || i=$((i+1)); done; if [ $i -gt 0 ]; then exit 1; fi;'; fi;
        # - if [ "$TRAVIS_BRANCH" != "master" ]; then docker run --rm pyiron/damask /bin/bash -c 'source /opt/conda/bin/activate; i=0; for f in $(ls ~/*.ipynb); do jupyter nbconvert --ExecutePreprocessor.timeout=9999999 --to notebook --execute $f || i=$((i+1)); done; if [ $i -gt 0 ]; then exit 1; fi;'; fi;
      deploy:
        - provider: script
          skip_cleanup: true
          script: ./.ci_support/deploy.sh
          on:
             all_branches: true
             repo: pyiron/docker-stacks
