jobs:
  include:
    - stage: Build Docker Images
      install:
        - export TODAY=$(date +%F)
        - docker build -t pyiron/base:latest pyiron-base/
        - docker tag pyiron/base:latest pyiron/base:"$TODAY"
        - docker build -t pyiron/atomistic:latest pyiron-atomistic/
        - docker tag pyiron/atomistic:latest pyiron/atomistic:"$TODAY"
        - docker build -t pyiron/md:latest pyiron-md/
        - docker tag pyiron/md:latest pyiron/md:"$TODAY"
        - docker build -t pyiron/sphinx:latest pyiron-sphinxdft/
        - docker tag pyiron/sphinx:latest pyiron/sphinx:"$TODAY"
        - docker build -t pyiron/dft:latest pyiron-dft/
        - docker tag pyiron/dft:latest pyiron/dft:"$TODAY"
        - docker build -t pyiron/pyiron:latest pyiron/
        - docker tag pyiron/pyiron:latest pyiron/pyiron:"$TODAY"
        - docker images
      script: 
        - docker run --rm pyiron/pyiron /bin/bash -c 'source /opt/conda/bin/activate; for f in $(ls ~/*.ipynb); do jupyter nbconvert --ExecutePreprocessor.timeout=9999999 --to notebook --execute $f; done;'
      deploy:
        - provider: script
          skip_cleanup: true
          script: ./.ci_support/deploy.sh
          on:
             all_branches: true
             repo: pyiron/docker-stacks
