channels:
- conda-forge
dependencies:
- pyiron =0.5.1
- pyiron_atomistics =0.4.4
- pymatgen =2023.12.18
- pyscal =2.10.18
- maggma =0.60.0
- pyiron-data =0.0.27
- nglview =3.0.8
- lammps =2023.08.02=*openmpi*
- openkim-models =2021.01.28
