channels:
- conda-forge
dependencies:
- pyiron =0.5.2
- pyiron_atomistics =0.4.7
- pymatgen =2023.12.18
- pyscal =2.10.18
- maggma =0.60.2
- pyiron-data =0.0.27
- nglview =3.1.1
- lammps =2023.08.02=*openmpi*
- openkim-models =2021.01.28
