channels:
- conda-forge
- nodefaults
dependencies:
- lammps =2024.08.29=*openmpi*  # [unix]
- nglview =3.1.4
- pyiron =0.5.2
- pyiron-data =0.0.30
- pyiron_atomistics =0.8.1
- openkim-models =2021.01.28
