channels:
- conda-forge
dependencies:
- pyiron =0.5.2
- pyiron_atomistics =0.5.4
- pymatgen =2024.4.13
- pyscal =2.10.18
- maggma =0.65.0
- pyiron-data =0.0.29
- nglview =3.1.2
- lammps =2023.11.21=*openmpi*
- openkim-models =2021.01.28
