channels:
- conda-forge
dependencies:
- damask =3.0.0a8
- fenics =2019.1.0=*_42
- mshr =2019.1.0=*_9
- pyiron =0.5.2
- pyiron_base =0.8.2
- pyiron_atomistics =0.5.3
- pyiron_continuum =0.0.9
- pyiron_gpl =0.0.5
- pyiron-data =0.0.30
- pyvista =0.43.6
- sqsgenerator =0.3
- vtk =9.2.6
- seaborn =0.13.2
- nglview =3.1.2
- lammps =2024.02.07=*openmpi*
- openkim-models =2021.01.28
- git =2.42.0
- openmpi =4.1.6
