channels:
  - conda-forge
  - nodefaults
dependencies:
  - git =2.46.0
  - gxx
  - pyiron 
  - pyiron_atomistics =0.7
  - pyiron-data =0.0.30
  - nglview =3.1.4
  - lammps =2024.06.27=*openmpi*
  - openkim-models =2021.01.28
  - nbgitpuller =1.2.2
  - python-ace =0.3.0
  - calphy =1.4.3
  - pyxtal =1.0.9
  - sphinxdft =3.1
  - numpy >1.20,<2
  - ase =3.25.0
  - damask =3.0.2
  - requests =2.32.4
  - matplotlib
  - pyiron_workflow =0.12.0
  - pyironflow =0.0.9
  - pip
  - pip:
    - git+https://github.com/pmrv/python-ace.git
    - tensorpotential ==0.4.5
