channels:
- conda-forge
- nodefaults
dependencies:
- pyiron_experimental =0.0.3
- temmeta =0.0.6
- pyprismatic =2.0.0
- match-series =1.0.4
- pyxem =0.19.1
- pystem =0.0.26
- scanf =1.5.2
- hyperspy =2.1.1
