channels:
- conda-forge
- nodefaults
dependencies:
- atomicrex =1.0.4
- calphy =1.4.3
- nbgitpuller =1.2.2
- pyiron_potentialfit =0.3.12
- python-ace =0.3.1 # [unix]
- pyxtal =1.1.1
- runner =1.3
- structdbrest =0.0.1
