channels:
- conda-forge
dependencies:
- atomicrex =1.0.3
- runner =1.2
- structdbrest =0.0.1
- pyiron_contrib =0.1.16
- pyiron_gpl =0.0.5
- nbgitpuller =1.2.1
- python-ace =0.2.8
- calphy =1.3.7
- pyxtal =0.6.2
