channels:
- conda-forge
- nodefaults
dependencies:
- atomicrex =1.0.3
- runner =1.2
- structdbrest =0.0.1
- pyiron_potentialfit =0.3.7
- pyiron_gpl =0.0.5
- nbgitpuller =1.2.2
- python-ace =0.3.0
- calphy =1.3.13
- pyxtal =1.0.6
