channels:
- conda-forge
dependencies:
- atomicrex =1.0.3
- runner =1.2
- structdbrest =0.0.1
- pyiron_contrib =0.1.6
- pyiron_gpl =0.0.3
- nbgitpuller =1.1.1
- libmamba =1.1.0
- pip
- pip:
    - pyace-lite
